apiVersion: apps/v1
kind: Deployment
metadata:
  name: appiecal-idp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appiecal-idp
  template:
    metadata:
      labels:
        app: appiecal-idp
    spec:
      containers:
      - name: appiecal-idp
        image: ghcr.io/ijskoud/appiecal-idp@sha256:b4d35a741b4d1640a9ad064b9d5f4f5148aef70a3d5a56a5869009e9184676ce
        ports:
        - containerPort: 8080
