apiVersion: apps/v1
kind: Deployment
metadata:
  name: appiecal-idp
  namespace: default
  annotations:
    secrets.phase.dev/redeploy: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appiecal-idp
  template:
    metadata:
      labels:
        app: appiecal-idp
    spec:
      containers:
        - name: appiecal-idp
          image: ghcr.io/ijskoud/appiecal-idp@sha256:5b765ee17efe7b47112754d900c7853343cae23ec8af0b04f2669483aaf09223
          ports:
            - containerPort: 8080
          env:
            - name: IDP_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: appiecal-secrets
                  key: IDP_ENCRYPTION_KEY
            - name: JDBC_URL
              valueFrom:
                secretKeyRef:
                  name: appiecal-secrets
                  key: JDBC_URL
            - name: JWKS_URL
              valueFrom:
                secretKeyRef:
                  name: appiecal-secrets
                  key: JWKS_URL
