apiVersion: apps/v1
kind: Deployment
metadata:
  name: appiecal-web-web
  namespace: default
  annotations:
    secrets.phase.dev/redeploy: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appiecal-web-web
  template:
    metadata:
      labels:
        app: appiecal-web-web
    spec:
      containers:
        - name: appiecal-web-web
          image: ghcr.io/ijskoud/appiecal-web-web@sha256:9be8f32844883cd40b9042c23e98aee55741b2862ebf34f092cf2a543f512c34
          ports:
            - containerPort: 3000
          env:
            - name: GRAPHQL_BACKEND_URL
              valueFrom:
                secretKeyRef:
                  name: appiecal-web-web-secrets
                  key: GRAPHQL_BACKEND_URL
            - name: GRAPHQL_SCHEMA_URL
              valueFrom:
                secretKeyRef:
                  name: appiecal-web-web-secrets
                  key: GRAPHQL_BACKEND_URL
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: appiecal-web-web-secrets
                  key: NEXTAUTH_SECRET
            - name: NEXTAUTH_URL
              valueFrom:
                secretKeyRef:
                  name: appiecal-web-web-secrets
                  key: NEXTAUTH_URL
            - name: AUTHENTIK_ISSUER
              valueFrom:
                secretKeyRef:
                  name: appiecal-web-web-secrets
                  key: AUTHENTIK_ISSUER
            - name: AUTHENTIK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: appiecal-web-web-secrets
                  key: AUTHENTIK_CLIENT_SECRET
            - name: AUTHENTIK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: appiecal-web-web-secrets
                  key: AUTHENTIK_CLIENT_ID
