apiVersion: apps/v1
kind: Deployment
metadata:
  name: appiecal-schedule
  namespace: default
  annotations:
    secrets.phase.dev/redeploy: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appiecal-schedule
  template:
    metadata:
      labels:
        app: appiecal-schedule
    spec:
      containers:
        - name: appiecal-schedule
          image: ghcr.io/ijskoud/appiecal-schedule@sha256:f0738be8db30df882999c383de4efe5f0c12801b8c05fb9c168c15de55563b78
          ports:
            - containerPort: 8080
          env:
            - name: JDBC_URL
              valueFrom:
                secretKeyRef:
                  name: appiecal-schedule-secrets
                  key: JDBC_URL
            - name: JWKS_URL
              valueFrom:
                secretKeyRef:
                  name: appiecal-schedule-secrets
                  key: JWKS_URL
