apiVersion: secrets.phase.dev/v1alpha1
kind: PhaseSecret
metadata:
  name: appiecal-calendar-secret-manager
  namespace: default
spec:
  phaseApp: 'appiecal'
  phaseAppEnv: 'production'
  phaseAppEnvPath: '/apps/calendar'
  phaseHost: 'https://phase.rpi-2.home.klrnbk.nl'
  pollingInterval: 60
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: 'phase-service-token'
        secretNamespace: 'default'
  managedSecretReferences:
    - secretName: 'appiecal-calendar-secrets' # Name of the Kubernetes managed secret that Phase will sync
      secretNamespace: 'default'
