apiVersion: apps/v1
kind: Deployment
metadata:
  name: appiecal-web-gql
  namespace: default
  annotations:
    secrets.phase.dev/redeploy: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appiecal-web-gql
  template:
    metadata:
      labels:
        app: appiecal-web-gql
    spec:
      containers:
        - name: appiecal-web-gql
          image: ghcr.io/ijskoud/appiecal-web-gql@sha256:75b52f795d5cd71e932f29bf81d13aaaba2a3d397457c6077f80d1caed73128c
          ports:
            - containerPort: 4000
          env:
            - name: BASE_API_URL
              valueFrom:
                secretKeyRef:
                  name: appiecal-web-gql-secrets
                  key: BASE_API_URL
