apiVersion: apps/v1
kind: Deployment
metadata:
  name: appiecal-web-gql
  namespace: default
  annotations:
    secrets.phase.dev/redeploy: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appiecal-web-gql
  template:
    metadata:
      labels:
        app: appiecal-web-gql
    spec:
      containers:
        - name: appiecal-web-gql
          image: ghcr.io/ijskoud/appiecal-web-gql@sha256:078b31354525c6e19146945322450d4d51bf1d9a8309e3dad5e8a2b3de7eb9f5
          ports:
            - containerPort: 4000
          env:
            - name: BASE_API_URL
              valueFrom:
                secretKeyRef:
                  name: appiecal-web-gql-secrets
                  key: BASE_API_URL
