apiVersion: apps/v1
kind: Deployment
metadata:
  name: appiecal-web-gql
  namespace: default
  annotations:
    secrets.phase.dev/redeploy: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appiecal-web-gql
  template:
    metadata:
      labels:
        app: appiecal-web-gql
    spec:
      containers:
        - name: appiecal-web-gql
          image: ghcr.io/ijskoud/appiecal-web-gql@sha256:b444127fa671d572009ab2574e44764170fd8b8aa6f7383b58b10c9fb4ae83ec
          ports:
            - containerPort: 4000
          env:
            - name: BASE_API_URL
              valueFrom:
                secretKeyRef:
                  name: appiecal-web-gql-secrets
                  key: BASE_API_URL
